---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-bookapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-bookapp
  template:
    metadata:
      labels:
        app: spring-bookapp
    spec:
      containers:
        - name: spring-bookapp
          image: zaidmohammad038/Springboot-bookApp-monitoring-using_prometheus-grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_APPLICATION_NAME
              value: Springboot-bookApp-monitoring-using_prometheus-grafana
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/myapplication?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

---
apiVersion: v1
kind: Service
metadata:
  name: spring-bookapp-service
spec:
  type: NodePort
  selector:
    app: spring-bookapp
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      nodePort: 30088
